name: REST API Manual Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      nationality:
        # nationality of a randomuser
        description: 'Nationality of a randomuser (AU, BR, CA, CH, DE, DK, ES, FI, FR, GB, IE, IN, IR, MX, NL, NO, NZ, RS, TR, UA, US)'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Call REST API
      id: step1
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://randomuser.me/api/?nat=${{ inputs.nationality }}"
        method: 'GET'
        username: ${{ secrets.AWX_USER }}
        password: ${{ secrets.AWX_PASSWORD }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
    - name: Show Response
      run: |
        echo ${{ steps.step1.outputs.response }}
        echo ${{ steps.step1.outputs.headers }}
        echo ${{ fromJson(steps.step1.outputs.response).results[0].name.first }}
        echo ${{ fromJson(steps.step1.outputs.response).results[0].location.country }}
