name: Sonarsource workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      project-id:
        # Sonar project id
        description: 'Sonar project ID'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Call REST API
      run: |
        curl -X GET "https://random-data-api.com/api/users/random_user"
  delete:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      id: step1
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://random-data-api.com/api/users/random_user"
        method: 'GET'
        username: ${{ secrets.AWX_USER }}
        password: ${{ secrets.AWX_PASSWORD }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
    - name: Show Response
      run: |
        echo ${{ steps.step1.outputs.response }}
        echo ${{ steps.step1.outputs.headers }}
        echo ${{ fromJson(steps.step1.outputs.response).uid }}
