name: Sonarsource Workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      organization:
        # Ord ID on Sonarsource
        description: 'Organization ID'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      project-name:
        # Sonarsource project name
        description: 'Sonarsource project name'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      github-repo:
        # Github repository name
        description: 'Github repository name'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Call REST API
      id: step1
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://sonarcloud.io/api/projects/create"
        method: 'POST'
        username: ${{ secrets.SONAR_TOKEN }}
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"project": "value_1", "organization": "value_2","name": "value_2"}'
    - name: Show Response
      run: |
        echo ${{ steps.step1.outputs.response }}
        echo ${{ steps.step1.outputs.headers }}
        echo ${{ fromJson(steps.step1.outputs.response).results[0].name.first }}
        echo ${{ fromJson(steps.step1.outputs.response).results[0].location.country }}
